[package]
name = "uniserver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasi-common = "22.0.0"
wasmtime = "22.0.0"
